import type { SoundDef, SoundId } from './types';

const def = (partial: SoundDef): SoundDef => partial;

export const SOUND_CATALOG: Record<SoundId, SoundDef> = {
  'ui-tick': def({
    id: 'ui-tick',
    bus: 'ui',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 40,
    spatial: false,
    asset: 'assets/audio/ui/tick.wav',
  }),
  'ui-hover': def({
    id: 'ui-hover',
    bus: 'ui',
    priority: 'low',
    volume: 0.1,
    cooldownMs: 80,
    spatial: false,
    group: 'ui-hover',
    asset: 'assets/audio/ui/hover.wav',
  }),
  'ui-click': def({
    id: 'ui-click',
    bus: 'ui',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 50,
    spatial: false,
    asset: 'assets/audio/ui/click.wav',
  }),
  'ui-confirm': def({
    id: 'ui-confirm',
    bus: 'ui',
    priority: 'high',
    volume: 0.28,
    cooldownMs: 80,
    spatial: false,
    asset: 'assets/audio/ui/confirm.wav',
  }),
  'ui-back': def({
    id: 'ui-back',
    bus: 'ui',
    priority: 'medium',
    volume: 0.18,
    cooldownMs: 80,
    spatial: false,
    asset: 'assets/audio/ui/back.wav',
  }),
  'ui-select-ninja': def({
    id: 'ui-select-ninja',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-ninja.wav',
  }),
  'ui-select-cole': def({
    id: 'ui-select-cole',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-cole.wav',
  }),
  'ui-select-death': def({
    id: 'ui-select-death',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-death.wav',
  }),
  'ui-select-rope': def({
    id: 'ui-select-rope',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-rope.wav',
  }),
  'ui-select-witch': def({
    id: 'ui-select-witch',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-witch.wav',
  }),
  'ui-select-shadow': def({
    id: 'ui-select-shadow',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-shadow.wav',
  }),
  'ui-match-start': def({
    id: 'ui-match-start',
    bus: 'ui',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/ui/match-start.wav',
  }),
  'objective-spawn': def({
    id: 'objective-spawn',
    bus: 'ui',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/ui/objective-spawn.wav',
  }),
  'objective-complete': def({
    id: 'objective-complete',
    bus: 'ui',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 180,
    spatial: false,
    asset: 'assets/audio/ui/objective-complete.wav',
  }),
  'objective-contested': def({
    id: 'objective-contested',
    bus: 'ui',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 280,
    spatial: false,
    group: 'objective-contested',
    asset: 'assets/audio/ui/objective-contested.wav',
  }),
  'piggy-hit': def({
    id: 'piggy-hit',
    bus: 'combat',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 55,
    spatial: true,
    group: 'piggy-hit',
    asset: 'assets/audio/combat/piggy-hit.wav',
  }),
  'piggy-break': def({
    id: 'piggy-break',
    bus: 'combat',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/combat/piggy-break.wav',
  }),
  'crate-hit': def({
    id: 'crate-hit',
    bus: 'combat',
    priority: 'low',
    volume: 0.14,
    cooldownMs: 50,
    spatial: true,
    group: 'crate-hit',
    asset: 'assets/audio/combat/crate-hit.wav',
  }),
  'crate-break': def({
    id: 'crate-break',
    bus: 'combat',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/combat/crate-break.wav',
  }),
  'ui-xp': def({
    id: 'ui-xp',
    bus: 'ui',
    priority: 'low',
    volume: 0.12,
    cooldownMs: 90,
    spatial: false,
    group: 'xp',
    asset: 'assets/audio/ui/xp.wav',
  }),
  'ui-level-up': def({
    id: 'ui-level-up',
    bus: 'ui',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/ui/level-up.wav',
  }),
  'ui-victory': def({
    id: 'ui-victory',
    bus: 'ui',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/victory.wav',
  }),
  'ui-defeat': def({
    id: 'ui-defeat',
    bus: 'ui',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/defeat.wav',
  }),
  'ui-draw': def({
    id: 'ui-draw',
    bus: 'ui',
    priority: 'high',
    volume: 0.26,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/draw.wav',
  }),
  'ability-ready': def({
    id: 'ability-ready',
    bus: 'ui',
    priority: 'medium',
    volume: 0.3,
    cooldownMs: 80,
    spatial: false,
    group: 'ability-ready',
    asset: 'assets/audio/ui/ability-ready.wav',
  }),
  'ninja-light': def({
    id: 'ninja-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.34,
    cooldownMs: 70,
    spatial: true,
    group: 'ninja-light',
    asset: 'assets/audio/heroes/ninja/light.wav',
  }),
  'cole-light': def({
    id: 'cole-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.32,
    cooldownMs: 70,
    spatial: true,
    group: 'cole-light',
    asset: 'assets/audio/heroes/cole/light.wav',
  }),
  'death-light': def({
    id: 'death-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.38,
    cooldownMs: 90,
    spatial: true,
    group: 'death-light',
    asset: 'assets/audio/heroes/death/light.wav',
  }),
  'rope-light': def({
    id: 'rope-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 55,
    spatial: true,
    group: 'rope-light',
    asset: 'assets/audio/heroes/rope/light.wav',
  }),
  'witch-light': def({
    id: 'witch-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.26,
    cooldownMs: 80,
    spatial: true,
    group: 'witch-light',
    asset: 'assets/audio/heroes/witch/light.wav',
  }),
  'witch-skull-spawn': def({
    id: 'witch-skull-spawn',
    bus: 'hero',
    priority: 'low',
    volume: 0.14,
    cooldownMs: 30,
    spatial: true,
    group: 'witch-skull-spawn',
    asset: 'assets/audio/heroes/witch/skull-spawn.wav',
  }),
  'witch-skull-fire': def({
    id: 'witch-skull-fire',
    bus: 'hero',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 28,
    spatial: true,
    group: 'witch-skull-fire',
    asset: 'assets/audio/heroes/witch/skull-fire.wav',
  }),
  'witch-skull-impact': def({
    id: 'witch-skull-impact',
    bus: 'combat',
    priority: 'low',
    volume: 0.18,
    cooldownMs: 40,
    spatial: true,
    group: 'witch-skull-impact',
    asset: 'assets/audio/heroes/witch/skull-impact.wav',
  }),
  'witch-tombstone-cast': def({
    id: 'witch-tombstone-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/witch-tombstone-cast.wav',
  }),
  'witch-tombstone-rise': def({
    id: 'witch-tombstone-rise',
    bus: 'ability',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/witch-tombstone-rise.wav',
  }),
  'witch-skeleton-awaken': def({
    id: 'witch-skeleton-awaken',
    bus: 'minion',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/witch-skeleton-awaken.wav',
  }),
  'witch-hex-cast': def({
    id: 'witch-hex-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/witch-hex-cast.wav',
  }),
  'witch-hex-buff': def({
    id: 'witch-hex-buff',
    bus: 'ability',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 60,
    spatial: true,
    group: 'witch-hex-buff',
    asset: 'assets/audio/abilities/witch-hex-buff.wav',
  }),
  'witch-ult-cast': def({
    id: 'witch-ult-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 160,
    spatial: true,
    asset: 'assets/audio/abilities/witch-ult-cast.wav',
  }),
  'witch-ult-aura': def({
    id: 'witch-ult-aura',
    bus: 'ability',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/witch-ult-aura.wav',
  }),
  'witch-ult-hex': def({
    id: 'witch-ult-hex',
    bus: 'ability',
    priority: 'low',
    volume: 0.18,
    cooldownMs: 80,
    spatial: true,
    group: 'witch-ult-hex',
    asset: 'assets/audio/abilities/witch-ult-hex.wav',
  }),
  'shadow-light': def({
    id: 'shadow-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 70,
    spatial: true,
    group: 'shadow-light',
    asset: 'assets/audio/heroes/shadow-light.wav',
  }),
  'shadow-claw-mark': def({
    id: 'shadow-claw-mark',
    bus: 'combat',
    priority: 'low',
    volume: 0.2,
    cooldownMs: 180,
    spatial: true,
    group: 'shadow-claw-mark',
    asset: 'assets/audio/combat/shadow-claw-mark.wav',
  }),
  'shadow-claw-charge': def({
    id: 'shadow-claw-charge',
    bus: 'ability',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-claw-charge.wav',
  }),
  'shadow-claw-whoosh': def({
    id: 'shadow-claw-whoosh',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-claw-whoosh.wav',
  }),
  'shadow-claw-impact': def({
    id: 'shadow-claw-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.42,
    cooldownMs: 90,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-claw-impact.wav',
  }),
  'shadow-dash-whoosh': def({
    id: 'shadow-dash-whoosh',
    bus: 'ability',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-dash-whoosh.wav',
  }),
  'shadow-dash-impact': def({
    id: 'shadow-dash-impact',
    bus: 'ability',
    priority: 'medium',
    volume: 0.34,
    cooldownMs: 80,
    spatial: true,
    group: 'shadow-dash-impact',
    asset: 'assets/audio/abilities/shadow-dash-impact.wav',
  }),
  'shadow-rage-cast': def({
    id: 'shadow-rage-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 150,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-rage-cast.wav',
  }),
  'shadow-rage-loop': def({
    id: 'shadow-rage-loop',
    bus: 'ability',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/shadow-rage-loop.wav',
  }),
  'shadow-rage-active': def({
    id: 'shadow-rage-active',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 150,
    spatial: true,
    asset: 'assets/audio/abilities/shadow-rage-active.wav',
  }),
  'ninja-smoke': def({
    id: 'ninja-smoke',
    bus: 'ability',
    priority: 'high',
    volume: 0.42,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-smoke.wav',
  }),
  'ninja-kick-whoosh': def({
    id: 'ninja-kick-whoosh',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-kick-whoosh.wav',
  }),
  'ninja-kick-impact': def({
    id: 'ninja-kick-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.48,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-kick-impact.wav',
  }),
  'ninja-tornado-loop': def({
    id: 'ninja-tornado-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.22,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/ninja-tornado-loop.wav',
  }),
  'ninja-tornado-slash': def({
    id: 'ninja-tornado-slash',
    bus: 'ability',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 140,
    spatial: true,
    group: 'tornado-slash',
    asset: 'assets/audio/abilities/ninja-tornado-slash.wav',
  }),
  'cole-ball-cast': def({
    id: 'cole-ball-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/cole-ball-cast.wav',
  }),
  'cole-ball-impact': def({
    id: 'cole-ball-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.44,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/cole-ball-impact.wav',
  }),
  'cole-ball-chain': def({
    id: 'cole-ball-chain',
    bus: 'ability',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 50,
    spatial: true,
    group: 'cole-chain',
    asset: 'assets/audio/abilities/cole-ball-chain.wav',
  }),
  'cole-discharge': def({
    id: 'cole-discharge',
    bus: 'ability',
    priority: 'high',
    volume: 0.5,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/cole-discharge.wav',
  }),
  'cole-storm-loop': def({
    id: 'cole-storm-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.16,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/cole-storm-loop.wav',
  }),
  'cole-storm-warn': def({
    id: 'cole-storm-warn',
    bus: 'ability',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 180,
    spatial: true,
    group: 'storm-warn',
    asset: 'assets/audio/abilities/cole-storm-warn.wav',
  }),
  'cole-storm-strike': def({
    id: 'cole-storm-strike',
    bus: 'ability',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 220,
    spatial: true,
    group: 'storm-strike',
    asset: 'assets/audio/abilities/cole-storm-strike.wav',
  }),
  'death-gun-start': def({
    id: 'death-gun-start',
    bus: 'ability',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/death-gun-start.wav',
  }),
  'death-gun-shot': def({
    id: 'death-gun-shot',
    bus: 'ability',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 45,
    spatial: true,
    group: 'gun-shot',
    asset: 'assets/audio/abilities/death-gun-shot.wav',
  }),
  'death-smash-windup': def({
    id: 'death-smash-windup',
    bus: 'ability',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/death-smash-windup.wav',
  }),
  'death-smash-impact': def({
    id: 'death-smash-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.58,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/death-smash-impact.wav',
  }),
  'death-sweep-loop': def({
    id: 'death-sweep-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.2,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/death-sweep-loop.wav',
  }),
  'death-sweep-hit': def({
    id: 'death-sweep-hit',
    bus: 'ability',
    priority: 'medium',
    volume: 0.26,
    cooldownMs: 160,
    spatial: true,
    group: 'sweep-hit',
    asset: 'assets/audio/abilities/death-sweep-hit.wav',
  }),
  'rope-dash-fire': def({
    id: 'rope-dash-fire',
    bus: 'ability',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-dash-fire.wav',
  }),
  'rope-dash-snap': def({
    id: 'rope-dash-snap',
    bus: 'ability',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 70,
    spatial: true,
    asset: 'assets/audio/abilities/rope-dash-snap.wav',
  }),
  'rope-dash-zip': def({
    id: 'rope-dash-zip',
    bus: 'ability',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 70,
    spatial: true,
    asset: 'assets/audio/abilities/rope-dash-zip.wav',
  }),
  'rope-dash-whoosh': def({
    id: 'rope-dash-whoosh',
    bus: 'ability',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-dash-whoosh.wav',
  }),
  'rope-grab-fire': def({
    id: 'rope-grab-fire',
    bus: 'ability',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/rope-grab-fire.wav',
  }),
  'rope-grab-catch': def({
    id: 'rope-grab-catch',
    bus: 'ability',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-grab-catch.wav',
  }),
  'rope-grab-zip': def({
    id: 'rope-grab-zip',
    bus: 'ability',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-grab-zip.wav',
  }),
  'rope-grab-impact': def({
    id: 'rope-grab-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.44,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-grab-impact.wav',
  }),
  'rope-punch-jump': def({
    id: 'rope-punch-jump',
    bus: 'ability',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/rope-punch-jump.wav',
  }),
  'rope-punch-impact': def({
    id: 'rope-punch-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.5,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/rope-punch-impact.wav',
  }),
  'rope-spray-whip': def({
    id: 'rope-spray-whip',
    bus: 'ability',
    priority: 'medium',
    volume: 0.16,
    cooldownMs: 70,
    spatial: true,
    group: 'rope-spray-whip',
    asset: 'assets/audio/abilities/rope-spray-whip.wav',
  }),
  'rope-spray-loop': def({
    id: 'rope-spray-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.14,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/rope-spray-loop.wav',
  }),
  'rope-wrap': def({
    id: 'rope-wrap',
    bus: 'ability',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 160,
    spatial: true,
    group: 'rope-wrap',
    asset: 'assets/audio/abilities/rope-wrap.wav',
  }),
  'combat-hit': def({
    id: 'combat-hit',
    bus: 'combat',
    priority: 'medium',
    volume: 0.26,
    cooldownMs: 70,
    spatial: true,
    group: 'combat-hit',
    asset: 'assets/audio/combat/hit.wav',
  }),
  'combat-hit-heavy': def({
    id: 'combat-hit-heavy',
    bus: 'combat',
    priority: 'medium',
    volume: 0.34,
    cooldownMs: 90,
    spatial: true,
    group: 'combat-hit',
    asset: 'assets/audio/combat/hit-heavy.wav',
  }),
  'combat-hit-finisher': def({
    id: 'combat-hit-finisher',
    bus: 'combat',
    priority: 'high',
    volume: 0.42,
    cooldownMs: 110,
    spatial: true,
    group: 'combat-hit',
    asset: 'assets/audio/combat/hit-finisher.wav',
  }),
  'combat-block': def({
    id: 'combat-block',
    bus: 'combat',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 80,
    spatial: true,
    group: 'combat-block',
    asset: 'assets/audio/combat/block.wav',
  }),
  'combat-perfect': def({
    id: 'combat-perfect',
    bus: 'combat',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 90,
    spatial: true,
    asset: 'assets/audio/combat/perfect.wav',
  }),
  'combat-clash': def({
    id: 'combat-clash',
    bus: 'combat',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 90,
    spatial: true,
    asset: 'assets/audio/combat/clash.wav',
  }),
  'combat-ability-hit': def({
    id: 'combat-ability-hit',
    bus: 'combat',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 90,
    spatial: true,
    group: 'ability-hit',
    asset: 'assets/audio/combat/ability-hit.wav',
  }),
  'combat-knockback': def({
    id: 'combat-knockback',
    bus: 'combat',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 140,
    spatial: true,
    group: 'knockback',
    asset: 'assets/audio/combat/knockback.wav',
  }),
  'hero-death': def({
    id: 'hero-death',
    bus: 'combat',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/combat/hero-death.wav',
  }),
  'minion-attack': def({
    id: 'minion-attack',
    bus: 'minion',
    priority: 'low',
    volume: 0.14,
    cooldownMs: 160,
    spatial: true,
    group: 'minion-attack',
    asset: 'assets/audio/minions/attack.wav',
  }),
  'minion-hit': def({
    id: 'minion-hit',
    bus: 'minion',
    priority: 'low',
    volume: 0.12,
    cooldownMs: 120,
    spatial: true,
    group: 'minion-hit',
    asset: 'assets/audio/minions/hit.wav',
  }),
  'minion-death': def({
    id: 'minion-death',
    bus: 'minion',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 90,
    spatial: true,
    group: 'minion-death',
    asset: 'assets/audio/minions/death.wav',
  }),
};

export const BUS_GAIN: Record<SoundDef['bus'], number> = {
  ui: 0.7,
  combat: 0.85,
  ability: 1,
  hero: 0.9,
  minion: 0.45,
};

export const PRIORITY_BUDGET: Record<SoundDef['priority'], number> = {
  high: 5,
  medium: 7,
  low: 4,
};

export const LOOPING_ABILITIES: readonly string[] = [
  'ninja-tornado',
  'cole-thunderstorm',
  'death-bat-sweep',
  'rope-spray',
  'shadow-rage',
];

export const SPAMMY_ABILITY_HITS: readonly string[] = [
  'ninja-tornado',
  'cole-thunderstorm',
  'death-gun-barrage',
  'death-bat-sweep',
  'rope-spray',
];
