import type { SoundDef, SoundId } from './types';

const def = (partial: SoundDef): SoundDef => partial;

export const SOUND_CATALOG: Record<SoundId, SoundDef> = {
  'ui-tick': def({
    id: 'ui-tick',
    bus: 'ui',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 40,
    spatial: false,
    asset: 'assets/audio/ui/tick.wav',
  }),
  'ui-hover': def({
    id: 'ui-hover',
    bus: 'ui',
    priority: 'low',
    volume: 0.1,
    cooldownMs: 80,
    spatial: false,
    group: 'ui-hover',
    asset: 'assets/audio/ui/hover.wav',
  }),
  'ui-click': def({
    id: 'ui-click',
    bus: 'ui',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 50,
    spatial: false,
    asset: 'assets/audio/ui/click.wav',
  }),
  'ui-confirm': def({
    id: 'ui-confirm',
    bus: 'ui',
    priority: 'high',
    volume: 0.28,
    cooldownMs: 80,
    spatial: false,
    asset: 'assets/audio/ui/confirm.wav',
  }),
  'ui-back': def({
    id: 'ui-back',
    bus: 'ui',
    priority: 'medium',
    volume: 0.18,
    cooldownMs: 80,
    spatial: false,
    asset: 'assets/audio/ui/back.wav',
  }),
  'ui-select-ninja': def({
    id: 'ui-select-ninja',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-ninja.wav',
  }),
  'ui-select-cole': def({
    id: 'ui-select-cole',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-cole.wav',
  }),
  'ui-select-death': def({
    id: 'ui-select-death',
    bus: 'ui',
    priority: 'medium',
    volume: 0.24,
    cooldownMs: 90,
    spatial: false,
    asset: 'assets/audio/ui/select-death.wav',
  }),
  'ui-match-start': def({
    id: 'ui-match-start',
    bus: 'ui',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/ui/match-start.wav',
  }),
  'ui-xp': def({
    id: 'ui-xp',
    bus: 'ui',
    priority: 'low',
    volume: 0.12,
    cooldownMs: 90,
    spatial: false,
    group: 'xp',
    asset: 'assets/audio/ui/xp.wav',
  }),
  'ui-level-up': def({
    id: 'ui-level-up',
    bus: 'ui',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 200,
    spatial: false,
    asset: 'assets/audio/ui/level-up.wav',
  }),
  'ui-victory': def({
    id: 'ui-victory',
    bus: 'ui',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/victory.wav',
  }),
  'ui-defeat': def({
    id: 'ui-defeat',
    bus: 'ui',
    priority: 'high',
    volume: 0.3,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/defeat.wav',
  }),
  'ui-draw': def({
    id: 'ui-draw',
    bus: 'ui',
    priority: 'high',
    volume: 0.26,
    cooldownMs: 400,
    spatial: false,
    asset: 'assets/audio/ui/draw.wav',
  }),
  'ability-ready': def({
    id: 'ability-ready',
    bus: 'ui',
    priority: 'medium',
    volume: 0.3,
    cooldownMs: 80,
    spatial: false,
    group: 'ability-ready',
    asset: 'assets/audio/ui/ability-ready.wav',
  }),
  'ninja-light': def({
    id: 'ninja-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.34,
    cooldownMs: 70,
    spatial: true,
    group: 'ninja-light',
    asset: 'assets/audio/heroes/ninja/light.wav',
  }),
  'cole-light': def({
    id: 'cole-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.32,
    cooldownMs: 70,
    spatial: true,
    group: 'cole-light',
    asset: 'assets/audio/heroes/cole/light.wav',
  }),
  'death-light': def({
    id: 'death-light',
    bus: 'hero',
    priority: 'medium',
    volume: 0.38,
    cooldownMs: 90,
    spatial: true,
    group: 'death-light',
    asset: 'assets/audio/heroes/death/light.wav',
  }),
  'ninja-smoke': def({
    id: 'ninja-smoke',
    bus: 'ability',
    priority: 'high',
    volume: 0.42,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-smoke.wav',
  }),
  'ninja-kick-whoosh': def({
    id: 'ninja-kick-whoosh',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-kick-whoosh.wav',
  }),
  'ninja-kick-impact': def({
    id: 'ninja-kick-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.48,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/ninja-kick-impact.wav',
  }),
  'ninja-tornado-loop': def({
    id: 'ninja-tornado-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.22,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/ninja-tornado-loop.wav',
  }),
  'ninja-tornado-slash': def({
    id: 'ninja-tornado-slash',
    bus: 'ability',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 140,
    spatial: true,
    group: 'tornado-slash',
    asset: 'assets/audio/abilities/ninja-tornado-slash.wav',
  }),
  'cole-ball-cast': def({
    id: 'cole-ball-cast',
    bus: 'ability',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 100,
    spatial: true,
    asset: 'assets/audio/abilities/cole-ball-cast.wav',
  }),
  'cole-ball-impact': def({
    id: 'cole-ball-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.44,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/cole-ball-impact.wav',
  }),
  'cole-ball-chain': def({
    id: 'cole-ball-chain',
    bus: 'ability',
    priority: 'medium',
    volume: 0.28,
    cooldownMs: 50,
    spatial: true,
    group: 'cole-chain',
    asset: 'assets/audio/abilities/cole-ball-chain.wav',
  }),
  'cole-discharge': def({
    id: 'cole-discharge',
    bus: 'ability',
    priority: 'high',
    volume: 0.5,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/cole-discharge.wav',
  }),
  'cole-storm-loop': def({
    id: 'cole-storm-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.16,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/cole-storm-loop.wav',
  }),
  'cole-storm-warn': def({
    id: 'cole-storm-warn',
    bus: 'ability',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 180,
    spatial: true,
    group: 'storm-warn',
    asset: 'assets/audio/abilities/cole-storm-warn.wav',
  }),
  'cole-storm-strike': def({
    id: 'cole-storm-strike',
    bus: 'ability',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 220,
    spatial: true,
    group: 'storm-strike',
    asset: 'assets/audio/abilities/cole-storm-strike.wav',
  }),
  'death-gun-start': def({
    id: 'death-gun-start',
    bus: 'ability',
    priority: 'high',
    volume: 0.32,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/death-gun-start.wav',
  }),
  'death-gun-shot': def({
    id: 'death-gun-shot',
    bus: 'ability',
    priority: 'medium',
    volume: 0.2,
    cooldownMs: 45,
    spatial: true,
    group: 'gun-shot',
    asset: 'assets/audio/abilities/death-gun-shot.wav',
  }),
  'death-smash-windup': def({
    id: 'death-smash-windup',
    bus: 'ability',
    priority: 'high',
    volume: 0.34,
    cooldownMs: 120,
    spatial: true,
    asset: 'assets/audio/abilities/death-smash-windup.wav',
  }),
  'death-smash-impact': def({
    id: 'death-smash-impact',
    bus: 'ability',
    priority: 'high',
    volume: 0.58,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/abilities/death-smash-impact.wav',
  }),
  'death-sweep-loop': def({
    id: 'death-sweep-loop',
    bus: 'ability',
    priority: 'high',
    volume: 0.2,
    cooldownMs: 0,
    spatial: true,
    loop: true,
    asset: 'assets/audio/abilities/death-sweep-loop.wav',
  }),
  'death-sweep-hit': def({
    id: 'death-sweep-hit',
    bus: 'ability',
    priority: 'medium',
    volume: 0.26,
    cooldownMs: 160,
    spatial: true,
    group: 'sweep-hit',
    asset: 'assets/audio/abilities/death-sweep-hit.wav',
  }),
  'combat-hit': def({
    id: 'combat-hit',
    bus: 'combat',
    priority: 'medium',
    volume: 0.26,
    cooldownMs: 70,
    spatial: true,
    group: 'combat-hit',
    asset: 'assets/audio/combat/hit.wav',
  }),
  'combat-hit-heavy': def({
    id: 'combat-hit-heavy',
    bus: 'combat',
    priority: 'medium',
    volume: 0.34,
    cooldownMs: 90,
    spatial: true,
    group: 'combat-hit',
    asset: 'assets/audio/combat/hit-heavy.wav',
  }),
  'combat-block': def({
    id: 'combat-block',
    bus: 'combat',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 80,
    spatial: true,
    group: 'combat-block',
    asset: 'assets/audio/combat/block.wav',
  }),
  'combat-clash': def({
    id: 'combat-clash',
    bus: 'combat',
    priority: 'high',
    volume: 0.36,
    cooldownMs: 90,
    spatial: true,
    asset: 'assets/audio/combat/clash.wav',
  }),
  'combat-ability-hit': def({
    id: 'combat-ability-hit',
    bus: 'combat',
    priority: 'medium',
    volume: 0.22,
    cooldownMs: 90,
    spatial: true,
    group: 'ability-hit',
    asset: 'assets/audio/combat/ability-hit.wav',
  }),
  'combat-knockback': def({
    id: 'combat-knockback',
    bus: 'combat',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 140,
    spatial: true,
    group: 'knockback',
    asset: 'assets/audio/combat/knockback.wav',
  }),
  'hero-death': def({
    id: 'hero-death',
    bus: 'combat',
    priority: 'high',
    volume: 0.4,
    cooldownMs: 80,
    spatial: true,
    asset: 'assets/audio/combat/hero-death.wav',
  }),
  'minion-attack': def({
    id: 'minion-attack',
    bus: 'minion',
    priority: 'low',
    volume: 0.14,
    cooldownMs: 160,
    spatial: true,
    group: 'minion-attack',
    asset: 'assets/audio/minions/attack.wav',
  }),
  'minion-hit': def({
    id: 'minion-hit',
    bus: 'minion',
    priority: 'low',
    volume: 0.12,
    cooldownMs: 120,
    spatial: true,
    group: 'minion-hit',
    asset: 'assets/audio/minions/hit.wav',
  }),
  'minion-death': def({
    id: 'minion-death',
    bus: 'minion',
    priority: 'low',
    volume: 0.16,
    cooldownMs: 90,
    spatial: true,
    group: 'minion-death',
    asset: 'assets/audio/minions/death.wav',
  }),
};

export const BUS_GAIN: Record<SoundDef['bus'], number> = {
  ui: 0.7,
  combat: 0.85,
  ability: 1,
  hero: 0.9,
  minion: 0.45,
};

export const PRIORITY_BUDGET: Record<SoundDef['priority'], number> = {
  high: 5,
  medium: 7,
  low: 4,
};

export const LOOPING_ABILITIES: readonly string[] = [
  'ninja-tornado',
  'cole-thunderstorm',
  'death-bat-sweep',
];

export const SPAMMY_ABILITY_HITS: readonly string[] = [
  'ninja-tornado',
  'cole-thunderstorm',
  'death-gun-barrage',
  'death-bat-sweep',
];
